#!/usr/bin/env python3
"""
GitHub Issue Generator for AWS Documentation Updates

Reads pending updates from check-aws-updates.py output and creates
GitHub issues for manual review.
"""

import json
import os
import subprocess
import sys
from pathlib import Path


def create_github_issue(service: str, updates: list) -> bool:
    """Create a GitHub issue for a service's updates."""
    if not updates:
        return False

    title = f"docs({service}): AWS documentation updates detected"

    # Build issue body
    body_parts = [
        "## AWS Documentation Updates Detected",
        "",
        f"The following significant updates were found for **{service}**:",
        "",
    ]

    for update in updates:
        body_parts.extend(
            [
                f"### {update['title']}",
                "",
                f"**Published:** {update['published']}",
                f"**Link:** {update['link']}",
                "",
                update.get("description", "No description available."),
                "",
                "---",
                "",
            ]
        )

    body_parts.extend(
        [
            "## Action Checklist",
            "",
            f"- [ ] Review the AWS documentation at the links above",
            f"- [ ] Update `skills/{service}/SKILL.md` if needed",
            "- [ ] Update any supplementary documentation files",
            "- [ ] Update the `last_updated` field in SKILL.md frontmatter",
            "- [ ] Test any code examples that may have changed",
            "- [ ] Close this issue when complete",
            "",
            "---",
            "*This issue was automatically generated by the AWS documentation sync workflow.*",
        ]
    )

    body = "\n".join(body_parts)

    # Create labels
    labels = ["documentation", "aws-update", service]

    # Use gh CLI to create issue
    try:
        cmd = [
            "gh",
            "issue",
            "create",
            "--title",
            title,
            "--body",
            body,
            "--label",
            ",".join(labels),
        ]

        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        print(f"Created issue for {service}: {result.stdout.strip()}")
        return True
    except subprocess.CalledProcessError as e:
        print(f"Error creating issue for {service}: {e.stderr}")
        return False
    except FileNotFoundError:
        print("Error: gh CLI not found. Please install GitHub CLI.")
        return False


def main():
    # Determine paths
    script_dir = Path(__file__).parent
    repo_root = script_dir.parent
    tracking_dir = repo_root / "tracking"

    # Load pending updates
    updates_file = tracking_dir / "pending-updates.json"
    if not updates_file.exists():
        print("No pending updates file found. Run check-aws-updates.py first.")
        return 0

    with open(updates_file) as f:
        all_updates = json.load(f)

    if not all_updates:
        print("No updates to process.")
        return 0

    # Group updates by service
    updates_by_service = {}
    for update in all_updates:
        service = update["service"]
        if service not in updates_by_service:
            updates_by_service[service] = []
        updates_by_service[service].append(update)

    print(f"Found updates for {len(updates_by_service)} services")

    # Check for required labels (create if missing)
    ensure_labels_exist()

    # Create issues for each service
    issues_created = 0
    for service, updates in updates_by_service.items():
        if create_github_issue(service, updates):
            issues_created += 1

    print(f"\nCreated {issues_created} issues")

    # Clear pending updates after processing
    if issues_created > 0:
        with open(updates_file, "w") as f:
            json.dump([], f)

    return 0


def ensure_labels_exist():
    """Ensure required labels exist in the repository."""
    required_labels = {
        "documentation": "Documentation updates",
        "aws-update": "AWS documentation or feature update",
    }

    for label, description in required_labels.items():
        try:
            subprocess.run(
                ["gh", "label", "create", label, "--description", description],
                capture_output=True,
                check=False,
            )
        except (subprocess.CalledProcessError, FileNotFoundError):
            pass


if __name__ == "__main__":
    sys.exit(main())
